spring:
  cloud:
    azure:
      eventgrid:
        endpoint: "https://topic2115.polandcentral-1.eventgrid.azure.net/api/events"
        key: "iAmkJpYxyPZHxk3os/ATtDx0QXf4DWlEZO5ywi7dIz0="
      servicebus:
        connection-string: "Endpoint=sb://namespace2115.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=d2TPJmn96Ep/OWECeX3Vb8Rh5sSuG8A2k+ASbHKjABo="
    function:
      definition: consume
    stream:
      bindings:
        consume-in-0:
          destination: "que2115"
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
  jms:
    servicebus:
      namespace: namespace2115
      pricing-tier: Basic

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlserver://databaseserver2115.database.windows.net:1433;database=iot_database;user=root123@databaseserver2115;password=hard_shit123.:;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
server:
  port: 8000